### ISSUE TITLE
activeadmin_addons select2 ajax API should match select2

### ISSUE THREAD

**Issue by davidwparker** [platanus/activeadmin_addons#102]
There's a lot of fields here https://select2.github.io/examples.html#data-ajax that I'd like to use. In particular "data". 

Unfortunately, activeadmin_addons makes assumptions with "url" (https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_search.md#filter-usage), and I can't use my endpoint because it's just plain ol' `q=` and I can't modify the request URL.

I'd like to discuss maybe adding a "classic: true" option or something like that so others can use the standard/classic API from select2 to override things.

**Comment by ldlsegovia** [comment]
It is not the intention to convert the addons into a select2 wrapper. You can do it without addons with a custom input.
