### ISSUE TITLE
Allow scopes with search_select

### ISSUE THREAD

**Issue by stuffa** [platanus/activeadmin_addons#104]
This is an interesting gem, and adds a lot if nice features to AA, but unfortunately for me, I need to be able to specify a scope for :search_select so that I only see records that match a specific state.

**Comment by ldlsegovia** [comment]
I think you can achieve this in several ways:

1. **Providing a filtered  active admin's url:**

```ruby
 f.input :region_id, as: :search_select, url: admin_regions_path(q: { name_contains: 't'})
``` 

2. **Providing a custom endpoint that uses ransack**

```ruby
f.input :region_id, as: :search_select, url: "api/regions"
```

https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_search.md#options
Look the `url` option.
