### ISSUE TITLE
cannot select any results in Ajax Search

### ISSUE THREAD

**Issue by calvinsug** [platanus/activeadmin_addons#105]
I loved this gem because it is user friendly and I have used select2 without AJAX and it works nicely without any problems, i can select any result.
Then I try to use select2 with ajax Search and it works for the autocomplete with this code
`      f.input :album_id, as: :search_select, url: admin_albums_path,
              fields: [:title], display_name: 'title', minimum_input_length: 2,
              order_by: 'title_asc'`

but unfortunately, i cannot click/select the results shown in autocomplete, is it because of my activeadmin version @emilioeduardob  ?

I use Ruby 2.3.1 , Rails 4.2.5.2 , mongoid 5.2.0, and this active admin gems:
Using activeadmin 1.0.0.pre5 from git://github.com/activeadmin/activeadmin.git (at master@7c664ec)
Using activeadmin_addons 0.10.1
Using activeadmin-mongoid 0.2.1 from git://github.com/elia/activeadmin-mongoid.git (at rails4-mongoid5@3ff2ade)

**Comment by mf222** [comment]
Hi @calvinsug, it's been a while. I could't reproduce your error. Did you try upgrading your activeadmin and activeadmin_addons versions? 

If you still have this problem, could you please give us more context about your issue in a new issue?. 

Greetings!
