### ISSUE TITLE
Ignore case (upcase/downcase) in ajax search?

### ISSUE THREAD

**Issue by abrambailey** [platanus/activeadmin_addons#110]
It seems that the select2 ajax search is case sensitive. Is there some way to ignore case? Thanks!

**Comment by ldlsegovia** [comment]
The request on ajax search **is not** case sensitive.
![search](https://cloud.githubusercontent.com/assets/3026413/24582360/d9de28ac-1704-11e7-8dbf-4d9e324815a5.gif)



I've tested with sqlite, mysql and postgress and ransack always perform a case insensitive search.

It uses `LIKE`with sqlite and mysql
<img width="1257" alt="screen shot 2017-04-01 at 5 52 17 pm" src="https://cloud.githubusercontent.com/assets/3026413/24582364/f5cb34c4-1704-11e7-838d-d819548c1844.png">

It uses `ILIKE` with postgres
<img width="1257" alt="screen shot 2017-04-01 at 5 55 04 pm" src="https://cloud.githubusercontent.com/assets/3026413/24582372/15d78ef2-1705-11e7-9561-cab02e65452a.png">

I don't know why you are having this issue...
Always you can use your own endpoint (working with ransack gem) to perform custom queries. 
https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_search.md (check the url option)
