### ISSUE TITLE
Existing value not selected on ajax select

### ISSUE THREAD

**Issue by abrambailey** [platanus/activeadmin_addons#111]
The following is working well for me:

```ruby
f.input :form_factor_ids, label: "Form Factors", as: :search_select, url: administration_form_factors_path, fields: [:full_name], display_name: 'full_name', minimum_input_length: 2, order_by: 'full_name_asc'
```

However, when I reload the page as edit, the select field is empty. Is it possible to have the existing value selected?

**Comment by abrambailey** [comment]
It seems like you are loading it here, so not sure why it's not working for me. https://github.com/platanus/activeadmin_addons/blob/master/app/assets/javascripts/activeadmin_addons/select2.js#L153-L162

**Comment by ldlsegovia** [comment]
I've tested this using the same configuration as you and it works well.

```ruby
      f.input :category_id, label: "Form Factors",
                            as: :search_select,
                            url: admin_categories_path,
                            fields: [:name],
                            display_name: 'name',
                            minimum_input_length: 2,
                            order_by: 'name_asc'
```
![search1](https://cloud.githubusercontent.com/assets/3026413/24582506/b48e1938-1707-11e7-87a0-fa759c5f500d.gif)

Do you have the `form_factor_ids` attribute in your permitted params?
