### ISSUE TITLE
" rails g activeadmin_addons:install " is giving error.

### ISSUE THREAD

**Issue by ShivrajDeepsagar** [platanus/activeadmin_addons#114]
I am using  Active Admin 1.0.0.pre4. Rails 4.2.6 and ruby 2.2.4. I included the gem 'activeadmin_addon' in my  gemfile and ran bundle install. After that I ran 'rails g activeadmin_addons:install'. This is giving me thefollowing:

Could not find generator 'activeadmin_addons:install'. Maybe you meant 'active_admin:install', 'active_admin:assets' or 'active_admin:devise'

**Comment by ldlsegovia** [comment]
<img width="556" alt="screen shot 2017-04-01 at 6 52 47 pm" src="https://cloud.githubusercontent.com/assets/3026413/24582736/8b56851e-170c-11e7-9d99-1a8588ccda46.png">

I've created a fresh rails app with your config and the installer runs without problems.
Please, reopen if you have more accurate information about the problem.

**Comment by joshudev** [comment]
Just had this - restarted spring and it worked
