### ISSUE TITLE
select2 tags is not working.

### ISSUE THREAD

**Issue by ShivrajDeepsagar** [platanus/activeadmin_addons#115]
I followed the documentation and replaced 

`f.input :names, as: :select`
 with
`f.input :names, as: :tags`. This didn't work as told in the documentation. Even the autocomplete stoped working once I replaced :select with :tags.

Can anybody please help me with this?

**Comment by ldlsegovia** [comment]
do you have a `names` string attribute in your model?
do you see any js/rails error?

**Comment by ldlsegovia** [comment]
I've tested this with:

An `Invoice` model with a `number`attribute (`names`) in your case.
<img width="1267" alt="screen shot 2017-04-01 at 7 09 00 pm" src="https://cloud.githubusercontent.com/assets/3026413/24582833/b0d2e614-170e-11e7-8baa-6c8b6845f25a.png">

In ActiveAdmin...

```ruby
ActiveAdmin.register Invoice do
  permit_params :number

  form do |f|
    f.inputs "Details" do
      f.input :number, as: :tags
    end

    f.actions
  end
end
```
In the browser
![tags](https://cloud.githubusercontent.com/assets/3026413/24582848/1484a648-170f-11e7-9901-38e60dcba66f.gif)

In DB after save
<img width="764" alt="screen shot 2017-04-01 at 7 11 38 pm" src="https://cloud.githubusercontent.com/assets/3026413/24582850/1eae129e-170f-11e7-8da9-5f9d064124ac.png">

**Comment by ShivrajDeepsagar** [comment]
This is my input field : 
 Here I have dropdown on :user_id, :category_id and :subcategory_id. 
![2017-04-02-223030_1366x768_scrot](https://cloud.githubusercontent.com/assets/4251116/24589190/05dcc7b6-17f4-11e7-855d-2575b9ff0a54.png)

`permit_params :title, :category_id, :sub_category_id, :description, :name, :email, :user_id, :status
`
```
form multipart: true do |f|
    f.inputs "WantedEquipment Request Details" do
      f.input :user_id, as: :select, collection: User.active.pluck(:email, :id), include_blank: 'Select User', label: 'Requester'.html_safe
      f.input :name
      f.input :email
      f.input :title
      f.input :category_id, as: :select, collection: Category.roots.active.pluck(:name, :id), include_blank: 'Select Category', label: 'Category<abbr title="required">*</abbr>'.html_safe
      @sub_categories = {}
      if f.object.category_id.present?
        category = Category.active.where(id: f.object.category_id).first
        @sub_categories = Hash[category.children.active.pluck(:id, :name)] if category.present?
      end
      f.input :sub_category_id, as: :select, collection: @sub_categories.map{|id,name| [name,id] }, include_blank: 'Select Sub Category', label: 'Sub-Category<abbr title="required">*</abbr>'.html_safe
      f.input :description
      f.input :status
    end
    f.actions
  end
```
```
I have attached image before I use :tags in the place of :select. Once I use :tags the autocomplete dropdown disappears. Nothing works. And it's not showing any error on the console.
