### ISSUE TITLE
Disable select2 for date fields

### ISSUE THREAD

**Issue by quentindemetz** [platanus/activeadmin_addons#117]
Hi,

I need to select dates far in the past and the original activeadmin datepicker (three select boxes for year, month and day) work great, how can I disable select2 for these fields?

Thanks

**Comment by emilioeduardob** [comment]
Hey,
I think you can pass `default-select` as the inputs class name

https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_default.md
