### ISSUE TITLE
search_select instantiates the wrong class name

### ISSUE THREAD

**Issue by tbuehl** [platanus/activeadmin_addons#136]
`input :member_ids, as: :search_select` throws the exception `uninitialized constant Member`.

For the following relationship:

```ruby
has_many :group_members
has_many :members, -> { GroupMember.member }, through: :group_members, source: :person, class_name: 'Person'
```

The normal `select` field works correctly though:

```ruby
input :member_ids, as: :select
```

**Comment by mf222** [comment]
I can't reproduce your issue with simple `has_many` and `through` relations. 

If you still have issues with this, could you give me more context about your GroupMember and Member model _in a new issue_? Also I think that is not necessary to use `-> { GroupMember.member }`.

Best regards!
