### ISSUE TITLE
Selected List is not working 

### ISSUE THREAD

**Issue by sunloverz** [platanus/activeadmin_addons#138]
I did everything like described in [readme](https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_selected_list.md) but nothing works

It shows me an empty input, thats all 
![screenshot from 2017-08-18 21 34 57](https://user-images.githubusercontent.com/1597561/29466037-3dc4d954-845d-11e7-9dca-434bbd2a1bc1.png)

**Comment by ldlsegovia** [comment]
It sounds like the js is not loading. Make sure you have:

- the `active_admin.js.coffee` with the following content:

```
#= require active_admin/base
#= require activeadmin_addons/all
```

- and the `active_admin.scss` with the following content:

```
//= require activeadmin_addons/all
```
