### ISSUE TITLE
[Nested Select] parent id is incorrect when using inside a nested form

### ISSUE THREAD

**Issue by attiq** [platanus/activeadmin_addons#160]
I am trying to use nested_select inside a nested form. but it always return the parent value as "-1".

my form is as follow:

form do |f|
    f.inputs do
      f.input :email
      f.input :role_ids, as: :select, multiple: true, collection: Role.all.map {|r| [r.name.to_s, r.id]}
      f.input :is_active
    end

    f.inputs "Employee Details", for: [:employee_detail, f.object.new_record? ? EmployeeDetail.new : f.object.employee_detail] do |ed|
      ed.input :office_id, as: :nested_select, :fields => [:name],
              level_1: { attribute: :company_id, collection: Company.all },
              level_2: { attribute: :region_id },
              level_3: { attribute: :office_id }
      end
    f.actions
  end  

Each time when i select a company, and then try to select a region, it always sends the company_id_eq= -1. 

Please help.

Thanks

**Comment by btazi** [comment]
I have the exact same problem, did you find a solution ??

**Comment by btazi** [comment]
I managed to fix the issue: https://github.com/platanus/activeadmin_addons/pull/164
For now you can copy and paste this file /app/assets/javascripts/activeadmin_addons/inputs/nested-select.js from the repo to your app and edit this part:

```  
    if (!!parent) {
        var parentSelectorId = '#' + model + '_' + parent;
	if (!$(parentSelectorId).length) {
	  parentSelectorId = container.find('*[id*='+ parent +']')[0];
	}
        var parentSelector = $(parentSelectorId)[0];

        $(parentSelector).on('select2:select', setParentValue);
        $(parentSelector).on('select2:unselect', setParentValue);
      }
```

**Comment by attiq** [comment]
Thanks for your Solution, i was getting error  " container.find is not a function ", SO i have replaced

parentSelectorId = container.find('*[id*='+ parent +']')[0];

with

parentSelectorId = $(container).find('*[id*='+ parent +']')[0];

Working fine Now.
Thanks
