### ISSUE TITLE
Generator Not working

### ISSUE THREAD

**Issue by atish23** [platanus/activeadmin_addons#165]
"rails g activeadmin_addons:install" not making any changes in any file. We need to change the active_admin.js.coffee file manually.

**Comment by ldlsegovia** [comment]
I tried it with the latest version and it worked.

<img width="783" alt="screen shot 2018-02-02 at 16 22 53" src="https://user-images.githubusercontent.com/3026413/35751170-4a5a49e4-0836-11e8-96d5-fa1e2de8a2fb.png">
