### ISSUE TITLE
Wrong id for Toggleable Boolean

### ISSUE THREAD

**Issue by nedden** [platanus/activeadmin_addons#167]
Invalid characters '::' for id

<img width="529" alt="screen shot 2017-11-23 at 11 27 23" src="https://user-images.githubusercontent.com/96683/33160323-643147b4-d041-11e7-8ed7-c10637696b01.png">

**Comment by nedden** [comment]
#168

**Comment by nedden** [comment]
Hi! 
Yes, you right. We have to change class_name in 'data-model' too.
Can you give an example of **update** action? I didn't find out how to make it short and DRY.

**Comment by felbalart** [comment]
@nedden what do you mean by "_an example of **update** action?"_

If you mean overriding it like this:
```
controller do
  def update
  ...
```
This is not needed, as it uses the default update from AA, with its REST route (PATCH to the resource url)

**Comment by felbalart** [comment]
@nedden decided to add `demodulize` directly in the `class_name` method, among with an `underscore` that was also missing.
So closed your [PR](https://github.com/platanus/activeadmin_addons/pull/168/files) and did it in [#173](https://github.com/platanus/activeadmin_addons/pull/173/files)

Should be merged and gem having a new release soon.

Thanks again for great catch!
