### ISSUE TITLE
Undefined Method 'add_classes_to_body'

### ISSUE THREAD

**Issue by mmattm** [platanus/activeadmin_addons#171]
Do you have any idea why i have this error ? I'm on Rails 5.1

`/Users/.rvm/gems/ruby-2.4.1/gems/activeadmin_addons-1.1.0/lib/activeadmin_addons/active_admin_config.rb:2:in `alias_method': undefined method `add_classes_to_body' for class `ActiveAdmin::Views::Pages::Base' (NameError)`

**Comment by casecamp** [comment]
Facing same issue,any solution?

**Comment by xn** [comment]
https://github.com/activeadmin/activeadmin/issues/5288

**Comment by xn** [comment]
https://github.com/platanus/activeadmin_addons/pull/172

**Comment by akute** [comment]
@xn thanks a lot! Waiting for your PR to be merged to master.

**Comment by ldlsegovia** [comment]
https://rubygems.org/gems/activeadmin_addons/versions/1.1.1
