### ISSUE TITLE
tag column for enum not working for rails 5

### ISSUE THREAD

**Issue by vishaltps** [platanus/activeadmin_addons#177]
My ruby version is 2.4.2 and rails version is 5.1.4.
I added enum in my product model, it is working fine. but when i use 
		tag_column :quantity

it railses this error 

> no implicit conversion of Symbol into String

How can i fix it ?

**Comment by ldlsegovia** [comment]
I think this https://github.com/platanus/activeadmin_addons/commit/247c8c06214a804cc039ae31a0bd8dda5770d06a#diff-f6cf3160d48abfebc70e74b3a2d5f7a1R11 solves the problem. Can you confirm that?
You will need to install addons v1.2.0. Reopen if the issue persist. Thanks!
