### ISSUE TITLE
Select 2 not working in Filter Pop up of active_admin_flat_skin

### ISSUE THREAD

**Issue by vishaltps** [platanus/activeadmin_addons#178]
I used gem 'active_admin_flat_skin'  https://github.com/ayann/active_admin_flat_skin improve the ActiveAdmin UI. For Filter it pop up the form and than admin can filter things. activeadmin addon's select2 working fine in form but it is not working in filter form. options is not showing at all.

When i try with another gem 'active_admin_theme ' https://github.com/activeadmin-plugins/active_admin_theme.  it is working fine in filter form,

May be because of pop up , select 2 is not working.

Please check attached Screen shots 

![new customer cheers on demand](https://user-images.githubusercontent.com/16555538/34409614-d3a3c192-ebf0-11e7-8f34-1a4514a0ee87.png)
![customers cheers on demand](https://user-images.githubusercontent.com/16555538/34409617-d4189580-ebf0-11e7-925b-117969604dff.png)

Another theme's filter form

![categories cheers on demand](https://user-images.githubusercontent.com/16555538/34409616-d3df23fe-ebf0-11e7-8f84-e482f33dd24b.png)

**Comment by ldlsegovia** [comment]
I think active_admin_flat_skin is changing the css and, because of that, addons can't find the default filter panel classes. We do not provide support for active admin themes. Sorry
