### ISSUE TITLE
Tags with ActsAsTaggableOn

### ISSUE THREAD

**Issue by Onumis** [platanus/activeadmin_addons#179]
So I'm using the acts-as-taggable-on gem, with activeadmin 1.2 and activeadmin_addons 1.1.2.

I have a model called `Product` with `acts_as_taggable`, and in the AA page:

```ruby
f.inputs 'Tags' do
  f.input :tag_list, as: :tags,
                           collection: Product.tag_counts.most_used,
                           display_name: :name
end
```

This generates the HTML:

```html
<input id="product_tag_list" name="product[tag_list]" value="one two three" type="hidden">
<select id="product_tag_list" 
            class="tags-input select2-hidden-accessible" 
            data-model="product" 
            data-method="tag_list" 
            data-width="80%" 
            data-collection="[
             {"id":" three","text":" three","selected":"selected"},
             {"id":" two","text":" two","selected":"selected"},
             {"id":"one","text":"one","selected":"selected"},
             {"id":"three","text":"three"},
             {"id":"two","text":"two"}]" 
           name="product[virtual_tag_list_attr]" 
           tabindex="-1" 
           aria-hidden="true" 
           multiple="">
  <option value=" three"> three</option>
  <option value=" two"> two</option>
  <option value="one">one</option>
  <option value="three">three</option>
  <option value="two">two</option>
</select>
```

The problem here is that the select box now has "duplicates": 
- the tags specified as the collection
- the product tags, which all but the first one have a space before (example: `one`, ` two`, ` three`)

See: 

![image](https://user-images.githubusercontent.com/1113178/34410002-f77a16ec-ebab-11e7-91cc-9e522a8f1725.png)

Is this a known issue? 
Is it a problem with the tags implementation?
Thanks

**Comment by ldlsegovia** [comment]
We do not provide support for acts_as_taggable. But, if `Product.tag_counts.most_used` returns a ActiveRecord Collection or an array containing strings it will work.

Reading the ActsAsTaggable's README, I think you are working with a collection of `ActsAsTaggableOn::Tag` objects.

https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_tags.md

**Comment by Onumis** [comment]
Alright, I've digged into this found the problem and made a fix that suits my needs: https://github.com/whitesmith/activeadmin_addons/commit/cd1afd5899dbdcb978626beb3a8c25e408137b7d

Explanation:

1. When using the AR collection returned by ActsAsTaggableOn, or using an Array of strings, the method `SelectHelpers#array_to_select_options` would convert the array into a string:

`["one", "two", "three"].to_s => "one, two, three"`

this would cause the tags to contain spaces since the next step is to split by ',':

`"one, two, three".split(",") => ["one", " two", " three"]`

Fixed with: https://github.com/whitesmith/activeadmin_addons/commit/cd1afd5899dbdcb978626beb3a8c25e408137b7d#diff-edf59ccc6c1903054b7c4378990a6a41R7 

2. The hidden input with the select value was not rendered correctly since the tags were just concatenated into a string, without commas:

```HTML
<input id="product_tag_list" name="product[tag_list]" value="one two three" type="hidden">
```
When editing the tags, this would auto correct, but when left untouched, a bad tag list value would be submitted to the server, causing the tags to all be merged into a single one :\

Fixed with: https://github.com/whitesmith/activeadmin_addons/commit/cd1afd5899dbdcb978626beb3a8c25e408137b7d#diff-edf59ccc6c1903054b7c4378990a6a41R7

Let me know if you think this is worth a PR. 
Else I'll just leave this here in case someone else bumps into this issue.
Thanks!

**Comment by Onumis** [comment]
Ah, one more thing, this would in theory be solved with the optional arg: `value` but I think it is not working...

Judging by `load_control_attributes` here: https://github.com/platanus/activeadmin_addons/blob/master/app/inputs/tags_input.rb#L12
I guess it's missing a `load_data_attr(:value, value: ???)` but I could not figure out how that works.
