### ISSUE TITLE
Polymorphic relation issue with the select2 search

### ISSUE THREAD

**Issue by s101d1** [platanus/activeadmin_addons#182]
I'm trying to implement [select2 search](https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_search.md):

```
  f.input :member_id, as: :search_select, url: admin_users_path, fields: [:name]
```

The active admin model has `member` polymorphic relation:

```
belongs_to :member, :polymorphic => true
```
One of the possible associated model is User.

In this case, I want the select search field to search from User table.

When I tried, I got error:  ````undefined method `where' for Member:Module````

Is there a way to deal with this issue?

**Comment by oaestay** [comment]
Currently there is no way to use search with Polymorphic associations, as they not only need to set the associated resource's id, but they also need its type, and managing the values needed escapes a little from the scope of select2.

**Comment by thiagodiniz** [comment]
@oaestay Do you think that a PR with a proposal would be accepted?

I was thinking of listing to [change event at the select](https://select2.org/programmatic-control/add-select-clear-items#selecting-options) em fill a hidden input with the `_type`
