### ISSUE TITLE
nested_select undefined method for any level_ attribute

### ISSUE THREAD

**Issue by Abeleda** [platanus/activeadmin_addons#191]
Hi 

When I try your sample for nested_select [https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_nested_select.md]

I get the following error:

undefined method `country_id' for #<City:0x007faad5d3e5f0>
f.input :region_id, as: :nested_select,
                  level_1: { attribute: :country_id }

I trying to use a nested_select for a City model to select the Region

ActiveAdmin.register City do
  permit_params :name, :region_id

  form do |f|
    f.inputs do
      f.input :name
      f.input :region_id, as: :nested_select,
                  level_1: { attribute: :country_id }
    end
    f.actions
  end
end

Models:
--------
class Country < ApplicationRecord
end

class Region < ApplicationRecord
  belongs_to :country
end

class City < ApplicationRecord
  belongs_to :region
end

ActiveAdmins:
--------------
ActiveAdmin.register Country do
  permit_params :name
end

ActiveAdmin.register Region do
  permit_params :name, :country_id
end

ActiveAdmin.register City do
  permit_params :name, :region_id

  form do |f|
    f.inputs do
      f.input :name
      f.input :region_id, as: :nested_select,
                  level_1: { attribute: :country_id }
    end
    f.actions
  end
end

Using:
- rails: 5.1.4
- ruby: 2.4.0p0
- activeadmin: 1.2.0

Any idea ?

TIA

**Comment by ldlsegovia** [comment]
I think the input should be:

```ruby
ActiveAdmin.register City do
  permit_params :name, :region_id

  form do |f|
     f.inputs do
       f.input :name
       f.input :region_id, as: :nested_select,
                         level_1: { attribute: :country_id },
                         level_2: { attribute: :region_id }
    end
    f.actions
  end
end
```

`level_2` is redundant, I know... But was done like that to provide config options.

**Comment by Abeleda** [comment]
It works !!!

Thank you. 

Miguel Fung

 <http://www.abeleda.com/>

Tel.         +506 8948-8581
Email.     lfung@abeleda.com
Website. www.abeleda.com
 <http://www.abeleda.com/>
Este correo electrónico y cualquier archivo transmitido en él son confidenciales de ABELEDA y previstos solamente para el uso del individuo u organización a quien se dirige. Si usted ha recibido este correo electrónico por error, por favor notifique al encargado del sistema. Tome en cuenta que cualquier opinión presentada en este correo electrónico son solamente las del autor y no representan necesariamente los de la compañía. Finalmente, el destinatario debe comprobar este correo electrónico y cualquier archivo adjunto para verificar la presencia de virus. ABELEDA no acepta ninguna responsabilidad por daños causados por algún virus transmitido por este medio.

Antes de imprimir este e-mail piensa bien si es necesario… 


 Piensa Verde…
