### ISSUE TITLE
Issue with require_all 2.0

### ISSUE THREAD

**Issue by portwood** [platanus/activeadmin_addons#200]
Just discovered all of my Rails applications using activeadmin_addons 1.3 crash after today's update to the require_all gem. Not sure if it is an issue with the way activeadmin_addons uses require_all or if there is an issue with require_all.

Steps to reproduce:
1. Bundle a working application containing activeadmin_addons.
2. run the application
3. application crashes and gives a traceback

Workaround:
Update Gemfile with the following:
gem 'require_all', '~> 1.5'

**Comment by Alexey-Lukin** [comment]
Same issue
