### ISSUE TITLE
numeric_range_filter raises an excpetion

### ISSUE THREAD

**Issue by zivsplacer** [platanus/activeadmin_addons#206]
Hey,
Im trying to add a filter to an integer price field

filter :estimated_price, as: :numeric_range_filter

raises an exception:
Formtastic::UnknownInputError
Unable to find input class NumericRangeFilterInput

**Comment by kunashir** [comment]
What is your version of the gem?
I use `activeadmin_addons 1.3.0` and it works fine.

**Comment by ldlsegovia** [comment]
I can't reproduce in 1.6.0. I'm going to close this due to inactivity.
