### ISSUE TITLE
Suggestion: Split into sub-repos

### ISSUE THREAD

**Issue by seanfcarroll** [platanus/activeadmin_addons#212]
This is an awesome project!

I am interested in about half of the plugins. Would it be interesting to split this into a series of separate gems, and then perhaps also modify this repo so that it pre-bundles all of them.

That way it will be easy to pick and choose. I'd be happy to help out on splitting the smaller pieces out.

**Comment by ldlsegovia** [comment]
Thanks! like you like :) We want to avoid the troubles of maintaining multiple repositories and versions. It works for us the way it is.
