### ISSUE TITLE
Implement DropzoneJS ?

### ISSUE THREAD

**Issue by cle61** [platanus/activeadmin_addons#218]
Implement the script DropzoneJS (http://www.dropzonejs.com/) for file upload ?

**Comment by mf222** [comment]
Hi @cle61, this suggestion doesn't seem to be a relevant feature by the time now. If you feel like contributing by doing this, you could follow the contributing rules [here](https://github.com/platanus/activeadmin_addons#contributing). Your help and contribution will be always welcome!
