### ISSUE TITLE
Select 2 should accept the user typed text

### ISSUE THREAD

**Issue by Karthik-bp** [platanus/activeadmin_addons#219]
I have a doubt regarding Select 2 in active admin ,
 Currently working :
      We have collections of names which will be shown, names can be selected from the suggestion. 
     I Referred: https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_tags.md 

Actually needed : 
I should be able to select the names from suggestions and I should be able to type our own names (free text )

**Comment by ldlsegovia** [comment]
you can add the new values like this:

![tags](https://user-images.githubusercontent.com/3026413/44932896-802f6480-ad3d-11e8-8a8d-73eaeb853eea.gif)
