### ISSUE TITLE
Associated model name with field name returning "uninitialized constant"

### ISSUE THREAD

**Issue by anson2590** [platanus/activeadmin_addons#220]
I am using activeadmin - 1.2.1, activeadmin_addons - 1.1.2 and rails 5.1. I want to filter based on associated model field name so I have wriiten a filter below I have mentioned the code.
code:
   filter :customer_client_id,
         as: :search_select_filter,
         url: proc { customer_index_path },
         fields: %i[key name],
         display_name: 'name',
         minimum_input_length: 2,
         order_by: 'name_asc',
         label: 'Customers'

":customer_client_id" where customer is model name and client_id is field name, this works perfect if i use  select but if i use search_select_filter I am getting error saying "uninitialized constant". Can anyone help me fixing this issue.

**Comment by anson2590** [comment]
Can anyone please help me to fix this issue.

**Comment by ldlsegovia** [comment]
Related to this: https://github.com/platanus/activeadmin_addons/issues/133

**Comment by itkin** [comment]
+1 did anybody find a workaround ?

**Comment by koteswararaok519** [comment]
Placeholder is not working in this search_select_filter, can anyone help me on this
