### ISSUE TITLE
toggle_bool_column model_name issue

### ISSUE THREAD

**Issue by qdegraeve** [platanus/activeadmin_addons#224]
Hi, 

there is an problem with the `toggle_bool_column` feature when the model name has module or when a decorator is used. Permitted params are wrong because of `class_name` method in `lib/activeadmin_addons/support/custom_builder.rb`.

The workaround I found is to use `model.model_name.param_key` instead of `model.class.name.demodulize.underscore`. That avoid the `_decorator` and leave the module in the model name.

regards
Quentin

**Comment by ldlsegovia** [comment]
thanks @qdegraeve
