### ISSUE TITLE
Tag input behaving differently  in production and locally

### ISSUE THREAD

**Issue by jrajpal92** [platanus/activeadmin_addons#230]
```
   f.inputs "Misc Info" do
        f.input :misc_info_raw, label: false, as: :tags 
       end
   end


```
The above code works as drop down on the production
![image](https://user-images.githubusercontent.com/25629729/43404973-c78c9714-93e6-11e8-98b1-e7b9e44637df.png)

However it works fine on the local. 

![](https://lh3.googleusercontent.com/-OHdwHQ_NOcM/W18k9EUjJYI/AAAAAAAAgdk/5QqVixt9010s6DS2ACWEfZIRv71nJM68QCL0BGAYYCw/h215/2018-07-30.png)

Previously it used to run fine in both the cases, However the behaviour changed for some reasons even when the code was not changed at all.

**Comment by ldlsegovia** [comment]
Please, provide more information like Rails, active admin and addons versions and reopen.
