### ISSUE TITLE
toggle_bool_column failed to update because data-model had module name cut out

### ISSUE THREAD

**Issue by epsimatic** [platanus/activeadmin_addons#232]
The issue: I have Rails 4.x, AA 1.0.0pre1, activeadmin_addons-1.6.0, and the following AA setup:

```ruby
ActiveAdmin.register Ddm::BlockProxy do
  actions :index, :show, :edit, :update
  permit_params [:is_blocked]

  index do
    id_column
    toggle_bool_column :is_blocked
    actions
  end
```

It generates this HTML:

```html
<span id="toggle-block_proxy-vw_fact_scripts-is_blocked" class="toggle-bool-switch" data-model="block_proxy" data-object_id="vw_fact_scripts" data-field="is_blocked" data-url="/admin/ddm_block_proxies/vw_fact_scripts"></span>
```

When I click on it, it generates this POST request:

```
id=vw_fact_scripts&block_proxy%5Bis_blocked%5D=true
```

It returns `204`, but logs also tell us that: 

```
I, [2018-08-16T15:14:35.450936 #93491]  INFO -- : method=PATCH path=/admin/ddm_block_proxies/vw_fact_scripts format=json controller=Admin::DdmBlockProxiesController action=update status=204 duration=17.40 view=0.00 db=3.43 unpermitted_params=["block_proxy"] user_id=1 user_email=xxx user_role=admin_user remote_ip=127.0.0.1
``` 

### Bug 1

Update was unsuccessful, but it returned no error and the switch visually flipped on the page. I can on find out it failed after I reload page

### Bug 2 

The correct `data-model` name should be `ddm_block_proxy`

How to fix this one:

`activeadmin_addons-1.6.0/lib/activeadmin_addons/support/custom_builder.rb:47`:

```ruby
    def class_name
      model.class.name.underscore.gsub('/', '_')
    end
```

**Comment by difernandez** [comment]
Sorry for the late reply. I wasn't able to reproduce this with a later version. Maybe it was a change in our end, or maybe something changed in `model_name` or `param_key` at some point, but I tried with a model in a module (specifically, in an engine), and `data-model` was the expected one. I'm closing this, but feel free to let us know if it's still an issue and give us more detail to pinpoint when this happens
