### ISSUE TITLE
How to use tagging without a multiple select

### ISSUE THREAD

**Issue by Uelb** [platanus/activeadmin_addons#236]
Hi,

I'm trying to use a tag field but without a multiple select as we can see here in the first example : https://select2.org/tagging
It seems like it automatically convert my select field to a multiple one if I use as: :tags in my app. Is there a way to prevent that behavior ?

Thanks !

**Comment by jgmontoya** [comment]
It looks like [this](https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_default.md) is what you're looking for.

**Comment by Uelb** [comment]
Hey, I've stumbled upon the use case again and I don't think it works, I want to use tagging (dynamic option creation), but without a multiple select, only allowing the user to select one element. I found no way of doing that at all. I'm not sure whether I should open a new issue or not.

**Comment by jgmontoya** [comment]
Thanks for coming back at this, I had initially misunderstood the issue.
AFAIK this is currently not supported but it shouldn't be too hard to implement.

**Comment by difernandez** [comment]
Hi @Uelb ! We just addressed this in #322, you can now use the `tags` option on regular select2 form inputs. It's not yet released, but you can try it out from the master branch! Documentation for this [here](https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_default.md#options)
