### ISSUE TITLE
Should I create a pull request for my fork with intlTelInput integration?

### ISSUE THREAD

**Issue by mabdelfattah** [platanus/activeadmin_addons#239]
As per [contribution guide](https://github.com/platanus/activeadmin_addons/blob/master/docs/CONTRIBUTING.md), you said people should ask before creating pull requests.

I've added a new input type (:tel) which integrates with the javascript library intlTelnput, should I create a pull request for this input?
![image](https://user-images.githubusercontent.com/721987/46276841-6a96a000-c572-11e8-91d3-abb9006e87bf.png)

**Comment by mf222** [comment]
Hi @mabdelfattah it looks like an interesting feature. If you follow the contributing rules [here](https://github.com/platanus/activeadmin_addons#contributing) you can open a pull request and we will give you feedback if it's needed in order to merge.
