### ISSUE TITLE
Select2: Tab chain is broken

### ISSUE THREAD

**Issue by shivgarg5676** [platanus/activeadmin_addons#248]
If you hit tab after selecting an option from dropdown, tab goes to the navigation bar. This problem does not appear if select2 is not focused.

**Comment by mattolson** [comment]
This is due to a bug in select2 4.0.3. See https://github.com/platanus/activeadmin_addons/issues/263

One possible workaround is to pin your version of select2 to 4.0.2 by putting the following in your Gemfile:

```
gem 'select2-rails', '4.0.2'
```
