### ISSUE TITLE
Selected list

### ISSUE THREAD

**Issue by shri-hari93** [platanus/activeadmin_addons#251]
Hello,

I have 3 fields in my active admin form.
field 2 -> belongs to field 1 (this can be defined using nested list)
field 3 -> field 2 has many relation with field 3 (Ideally, this could be defined using selected list as per the documentation. However in my case the value of field 2 should be used dynamically to list the values for field 3)

How could I possibly achieve this?

**Comment by dmitry** [comment]
@shri-hari93 only custom solution can be applied. I think issue can be closed.

**Comment by rjherrera** [comment]
@dmitry I agree, if you still need help @shri-hari93 please feel free to comment on this issue again. Probably using custom javascript you can achieve what you needed.
