### ISSUE TITLE
Rails 4.1+ enum and activeadmin 1.0.0

### ISSUE THREAD

**Issue by maia** [platanus/activeadmin_addons#26]
What is the proper way of displaying tags for "enum" columns (Rails 4.1+) using activeadmin 1.0.0(.pre1)? I've never looked into the syntax of previous activeadmin versions, but 1.0.0 syntax is:
````
index do
  selectable_column
  column :title
  column :description
  column :status
  actions
end
````
Neither 'tag_row' nor 'tag_column' work, they lead to a NoMethodError with an undefined method in :ActiveAdmin::Views::IndexAsTable.

While it is possible to use a normal 'column', this won't display any tags (and is the default behavior, even without using activeadmin_addons).

In case activeadmin_addons is not fully compatible with the 1.0.0 series of activeadmin, I strongly suggest to add a note in the description of the addon indicating which parts work and which don't.

**Comment by emilioeduardob** [comment]
Hey Maia, I don't think activeadmin_addons supports Rails enums yet. It supports enums through the `enumerize` gem. But I think addons should also support the builtin enums in Rails

**Comment by bunzli** [comment]
what do you think @juliogarciag ?

**Comment by juliogarciag** [comment]
We can make it. I didn't used the Rails built-in enums but i don't think they're very different and maybe we  will eventually use them for the use cases of the `enumerize` gem in the future (because it's built-in). I think we can try to fix this on friday.
