### ISSUE TITLE
Tags doesn't work properly with has_and_belongs_to_many

### ISSUE THREAD

**Issue by brunofrank** [platanus/activeadmin_addons#260]
I had a many to many relationship and the input of tags doesn't work properly in this situation.

```
class Email < ApplicationRecord
  belongs_to :user
  belongs_to :customer
  has_and_belongs_to_many :quotes
```

```
  form do |f|
    inputs do
      input :customer      
      input :quotes, as: :tags, value: :id, display_name: :id
```

I tried everything and I can't make it work.

![image](https://user-images.githubusercontent.com/40139/56388445-5dcf5600-61fd-11e9-862f-288184bdc37c.png)

**Comment by reneweteling** [comment]
Same here

**Comment by ldlsegovia** [comment]
You need to add:

```ruby
ActiveAdmin.register Email do
  permit_params quote_ids: []

  form do |f|
    inputs do
      input :customer      
      input :quote_ids, as: :tags, display_name: :id, collection: Quote.all
    end
  end
end
```

In short:
- Provide the `collection` attribute.
- Use `_ids` suffix.
- Add to `permit_params`.

Sorry for the delayed answer :)
