### ISSUE TITLE
Fix Couldn't find 'sass-rails' error on initial setup

### ISSUE THREAD

**Issue by experimatt** [platanus/activeadmin_addons#261]
**Repro steps:**
1. Add `activeadmin_addons` to Gemfile (of a Rails 5 API-only project)
2. `bundle`
3. `$ rails g activeadmin_addons:install`

**Expected outcome:**
* Active Admin generator runs successfully

**Actual outcome:**
```
$ rails g activeadmin_addons:install
/Users/matt/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'activeadmin_addons'.
Gem Load Error is: Couldn't find 'sass-rails' or 'sassc-rails' gems in your application.
Backtrace for gem load error is:
/User/matt/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activeadmin_addons-1.7.1/lib/activeadmin_addons/engine.rb:12:in `rescue in rescue in <class:Engine>'
```

After adding `'sass-rails'` to my Gemfile and re-running `bundle`, the generator worked fine.

**Comment by mf222** [comment]
@experimatt we recommend you to install `sassc-rails` instead.

**Comment by experimatt** [comment]
@mf222 I did that, which solved my problem, but I feel like that dependency should be included in this gem, if it's needed.

**Comment by rjherrera** [comment]
@ldlsegovia what do you think about this? Currently `sassc-rails` is included only as a development dependency in the gemspec, should we include it as a normal one? I don't really see a reason behind one being included in dev and the other everywhere.

**Comment by ldlsegovia** [comment]
@rjherrera please include it as normal dependency
