### ISSUE TITLE
select2-rails is no longer maintained

### ISSUE THREAD

**Issue by mattolson** [platanus/activeadmin_addons#263]
I have been trying to work with the author of select2-rails to integrate a more recent version for over a year with no reply. It appears that the project is unmaintained. See https://github.com/argerim/select2-rails/issues/175 or look at the numerous PRs for upgrades that have not been looked at in 18 months: https://github.com/argerim/select2-rails/pulls

Because activeadmin_addons uses select2-rails as a dependency, we are stuck with version 4.0.3 (the latest published by select2-rails). However, 4.0.3 introduced an annoying bug which means that users can't tab through select fields with the tab key. This is the source of https://github.com/platanus/activeadmin_addons/issues/248. This bug affects me as well, and it was fixed in 4.0.4. See https://github.com/select2/select2/releases/tag/4.0.4

I think it would be smart for this project to vendor the select2 assets directly and stop relying on select2-rails, which is unmaintained and on an old version. Select2 is now up to 4.0.7, and it would be great to bring these changes in.

**Comment by AFlowOfCode** [comment]
Agreed. Unfortunately it's starting to look like this project is drifting towards being unmaintained as well.

**Comment by rjherrera** [comment]
@mattolson @AFlowOfCode I agree too. And we'd like to review #264 if it gets rebased, thanks for the heads up.
