### ISSUE TITLE
Two <body> sections in activeadmin views

### ISSUE THREAD

**Issue by bdezonia** [platanus/activeadmin_addons#273]
We are using activeadmin_addons in an older activeadmin based app (1.1.0). When we include your gem we get (non-fatal) HTML errors when viewing any set of model instances (for instance, Users). The HTML for the page always adds a second <body> section. The extra section looks like this:

body data-default-select="select2"
/body

(brackets elided since they would not render correctly in this markup language)

I am not sure if this is a problem with your gem or the select2-rails gem or something else. But if we remove your gem from our Gemfile the HTML is rendered correctly. Note that in our Gemfile.lock we are using the most up to date version of select2-rails (4.0.3).

**Comment by jgmontoya** [comment]
Hi @bdezonia could you check if this issue still exist? We've recently upgraded select2

**Comment by jgmontoya** [comment]
I'm closing some issues for housekeeping as we're trying to give some new life to this project. Feel free to reopen it if this is still a problem.

**Comment by bdezonia** [comment]
@jgmontoya I just tested the issue with 1.7.1 and our app and the bug is still present.

**Comment by jgmontoya** [comment]
Could you give it a try with the master branch? there have been some changes since (that are still not part of a release)

**Comment by bdezonia** [comment]
It's still a problem using master

**Comment by dirkjonker** [comment]
@bdezonia it should be fixed now with #302 could you check using master again?

**Comment by bdezonia** [comment]
Yes, it appears to be closed. Thanks and good work.
