### ISSUE TITLE
Select2 does not work with associations of other modules

### ISSUE THREAD

**Issue by letiesperon** [platanus/activeadmin_addons#275]
# Select2 does not work with associations of other modules

## Steps to reproduce:

I have the model `CompanyDatum` that has a foreign key called `business_company_id` to an association named `company`. 

The Company class is inside the `Business` module: `Business::Company`. 
When I use search select, it identifies that the class should be `BusinessCompany`, instead of `Business::Company`, raising an error. 

```
# app/admin/company_data.rb
      f.input :business_company_id, as: :search_select,
          url: admin_business_companies_path,
          fields: [:name], minimum_input_length: 2,
          predicate: 'starts_with',
          order_by: 'name_asc',
          class: 'Business::Company'
```

raises:

`uninitialized constant BusinessCompany`

(Not sure what the `class` option should do there but it's not fixing the issue)

--- 

It should inflect the association class from the association itself, instead of building it from the field.

**Comment by dariogf** [comment]
Hi,

I have just found the same issue but with a nested_select (and have fixed it for my case). Digging into the code I have found that in nested select this method is the culprit:

```ruby
#app/input/nested_select_input.rb:75

def instance_from_attribute_name(attribute)
    return unless attribute
    attribute_value = @object.send(attribute)
    return unless attribute_value
    klass = attribute.to_s.chomp("_id").camelize.constantize
    klass.find_by_id(attribute_value)
  end
```
It is better to ask the relation if infering with the attribute fails, but this makes mandatory that the models has the relation defined and I am not sure if the mantainers would like to add this.

```ruby
def instance_from_attribute_name(attribute)
    return unless attribute
    attribute_value = @object.send(attribute)
    return unless attribute_value
    klass = attribute.to_s.chomp("_id").camelize.constantize rescue nil
    if !klass
      klass=@object.class.reflect_on_association(attribute.to_s.chomp("_id")).klass
    end
    klass.find_by_id(attribute_value)
  end
```

**Comment by MrJoy** [comment]
Alternatively, something like this should work:

```rubyclass NestedSelectInput < ActiveAdminAddons::InputBase
  def instance_from_attribute_name(attribute)
    return unless attribute
    attribute_value = @object.send(attribute)
    return unless attribute_value
    attr = attribute.to_s
    assoc = @object
            .class
            .reflect_on_all_associations
            .find { |assoc| assoc.name.to_s == attr || assoc.foreign_key.to_s == attr }
    return unless assoc
    assoc.active_record.find_by(assoc.association_primary_key => attribute_value)
  end
end
```

This should be a bit more resilient, and handle cases where the column on the join table isn't named `id`.  Not sure it handles _every_ case properly though, so playing with exotic configurations of associations in test cases is recommended.
