### ISSUE TITLE
does toggleboolcolumn cannot work?

### ISSUE THREAD

**Issue by jessesongs** [platanus/activeadmin_addons#278]
i have tried many times.

**Comment by jessesongs** [comment]
![IMG_20191111_164952](https://user-images.githubusercontent.com/32221425/68575469-1a914900-04a7-11ea-9844-c3f4404bab50.jpg)
![IMG_20191111_164109](https://user-images.githubusercontent.com/32221425/68575483-23821a80-04a7-11ea-9293-0e83824011f0.jpg)
![IMG_20191111_163959](https://user-images.githubusercontent.com/32221425/68575489-2715a180-04a7-11ea-83fb-548f127cb2cf.jpg)

**Comment by rribeiro1** [comment]
Did you run the generator? 

`rails g activeadmin_addons:install`

**Reference:** https://github.com/platanus/activeadmin_addons (Installation)

**Comment by jessesongs** [comment]
hi，Ribeiro     i^m sure i run the generater， i use many small functions of this gem, all the functions work but toggle_bool_column，so i feel confused. i dont konw why.      thank you. 910294315 邮箱：910294315@qq.com 签名由 网易邮箱大师 定制 On 11/14/2019 05:44, Rafael Ribeiro wrote: Did you run the generator? rails g activeadmin_addons:install Reference: https://github.com/platanus/activeadmin_addons (Installation) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jessesongs** [comment]
HI，there.             I tried again，It works now.        THANK YOU  SO MUCH. 910294315 邮箱：910294315@qq.com 签名由 网易邮箱大师 定制 On 11/14/2019 10:55, 宋吉庆 wrote: hi，Ribeiro     i^m sure i run the generater， i use many small functions of this gem, all the functions work but toggle_bool_column，so i feel confused. i dont konw why.      thank you. 910294315 邮箱：910294315@qq.com 签名由 网易邮箱大师 定制 On 11/14/2019 05:44, Rafael Ribeiro wrote: Did you run the generator? rails g activeadmin_addons:install Reference: https://github.com/platanus/activeadmin_addons (Installation) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jgmontoya** [comment]
I will assume that @rribeiro1's comment solved your issue.
