### ISSUE TITLE
tag_column :status, interective: true based on resource column value

### ISSUE THREAD

**Issue by mohsinijaz568** [platanus/activeadmin_addons#299]
how can i add tag)column with interective true but based on resource column value on index page

**Comment by rjherrera** [comment]
Hi there! Could you explain your question a little bit more? I couldn't understand what you meant by "based on resource column value"

**Comment by ldlsegovia** [comment]
The `interactive: true` option only works with Rails enum or Enumerize attributes. You can't use another resource column value.
