### ISSUE TITLE
Not working with Rails 6, ActiveAdmin 2.7, and Sprockets 4

### ISSUE THREAD

**Issue by danielricecodes** [platanus/activeadmin_addons#317]
I just installed the gem, ran the generator, and the gem doesn't work.  Is it tested with Rails 6 and ActiveAmin 2.7?  Are there additional dependencies the README doesn't mention?

<img width="1441" alt="New_Zip_Code___MyPorter_Admin_and_my-porter-two-oh_—_fsevent_watch_◂_0_0_0_0_3000___my-porter-two-oh__rvm_bin_path__Users_danielrice__rvm_bin_TERM_PROGRAM_Apple_Terminal_—_202×55" src="https://user-images.githubusercontent.com/169038/89846767-66a91100-db3f-11ea-9c64-c0227a1355d6.png">

```
activeadmin (2.7.0)
activeadmin_addons (1.7.1)
sprockets (4.0.2)
sprockets-rails (3.2.1)
rails (6.0.3.2)
```

**Comment by jgmontoya** [comment]
Hi, which version of the gem are you currently using?

There have been some upgrades since the last release so maybe if you use it directly from github that may solve the issue.

**Comment by danielricecodes** [comment]
> which version of the gem are you currently using

activeadmin_addons (1.7.1)

**Comment by danielricecodes** [comment]
I figured out the problem - it was Sprockets 4.  When I forced Sprockets to downgrade, e.g. `gem 'sprockets', '< 4'`, Select2 loads as expected.

Moving forward, you should consider putting in a `sprockets` dependency in this gem's gemspec.

**Comment by danielricecodes** [comment]
Downgrading sprockets fixed it in development, but now that I've deployed to production the issue is back.  Very strange indeed.  The only difference in these screenshots is `Rails.env`.

<img width="1348" alt="Banners_and_Alerts_and_New_Zip_Code___MyPorter_Admin" src="https://user-images.githubusercontent.com/169038/91106079-0cc04500-e62f-11ea-8a47-94ceed9ab1e8.png">

**Comment by jgmontoya** [comment]
:thinking:  Could you try to use the gem directly from the master branch instead of v1.7.1? I'm not sure it will solve the issue but it's an easy thing to try first and help us debug.

If it doesn't work could you setup a minimal example for us to be able to reproduce the bug and look more into it?

**Comment by danielricecodes** [comment]
This is really really weird, but not having `//= require active_admin/base` as the first line in `active_admin.js` was the culprit.  I even upgraded back to Sprockets 4.  

<img width="934" alt="GitKraken" src="https://user-images.githubusercontent.com/169038/91121084-48b9d100-e654-11ea-88ad-30168a269443.png">
