### ISSUE TITLE
toggle_bool_field on a nested model?

### ISSUE THREAD

**Issue by single-stop-rj** [platanus/activeadmin_addons#318]
I am trying to use the toggle bool on the index to toggle a nested bool. 

Is this supported, and I just cant see it? 

ie book index but 

book.author.alive?

**Comment by sleivav** [comment]
Why do you want to access a nested attribute from the index? If this is a common use case I'll try to look into it, but for now I'd suggest editing that attribute from the author model

**Comment by ldlsegovia** [comment]
It is not supported and there are no plans to do so at the moment.
