### ISSUE TITLE
JavaScript Error: No select2/compat/initSelection in edit views with search_select fields

### ISSUE THREAD

**Issue by halilim** [platanus/activeadmin_addons#32]
(Versions: Ruby: 2.2.3, Rails: 4.2.4, Active Admin: master, activeadmin_addons: master)

select2 v. 4.0 comes with some changes, one of them being the [removal of `initSelection `](https://select2.github.io/announcements-4.0.html#removed-initselection).

#### Workaround

Bundle `select2-rails` gem yourself with a pre-4 version:

```ruby
gem 'select2-rails', '~> 3.5.9'
gem 'activeadmin_addons'
```

#### Temporary fix
Specify a `select2-rails` version in the `gemspec` file:

```ruby
s.add_dependency "select2-rails", "~> 3.5.9"
```
I was planning to make a pull request with this fix but I thought you might want to update the JS code to use select2 v4 instead.

**Comment by ldlsegovia** [comment]
@halilim we think `v3.5.9` is enough right now. Thanks

**Comment by datenimperator** [comment]
This bit me badly today. Our project is using select2 4.0+ and after a `bundle update`  our JS code didn't work anymore – because select2 had been downgraded to 3.5.x

Given that 4.0 will be the way to go, is there a way to upgrade this gem to be compatible?

**Comment by ldlsegovia** [comment]
I think there is not an easy way. There is an open issue: https://github.com/platanus/activeadmin_addons/issues/56, if you want to collaborate.

Related files are:
* https://github.com/platanus/activeadmin_addons/blob/master/app/assets/javascripts/activeadmin_addons/select2.js
* https://github.com/platanus/activeadmin_addons/blob/master/app/inputs/nested_select_input.rb
* https://github.com/platanus/activeadmin_addons/blob/master/app/inputs/search_select_input.rb
* https://github.com/platanus/activeadmin_addons/blob/master/app/inputs/tags_input.rb

The select2 functionality is covered here: 

* https://github.com/platanus/activeadmin_addons/blob/master/spec/features/select_2_spec.rb
