### ISSUE TITLE
Activeadmin Reorderable

### ISSUE THREAD

**Issue by kwent** [platanus/activeadmin_addons#329]
## Activeadmin Reorderable

Hi,

Any interests in integrating a drag and drop reorder library as: https://github.com/vigetlabs/activeadmin_reorderable ?

Regards

**Comment by rjherrera** [comment]
hi @kwent! Do you mean adding it as part of this gem? Have you tried using it together with it, or does it break or something? I feel like it is a specific use case, but I would be happy to discuss it if you mean including it as another dependency here.

**Comment by kwent** [comment]
I was thinking of including it a part of `activeadmin_addons`. I done many Rails project and always found myself installing `activeadmin_addons` + a reorder library. I don't think it's that uncommon to reorder records in table. Like blog posts / pages etc for examples.

**Comment by difernandez** [comment]
Hi @kwent! We're reluctant to add a new dependency, especially one that we haven't had the need to use and seems to work fine alongside this gem. Plus, the gem apparently [doesn't support webpacker](https://github.com/vigetlabs/activeadmin_reorderable/issues/8) and we've recently made [efforts to support it](https://github.com/platanus/activeadmin_addons/pull/319).

I'm closing this issue, but please feel free to open a new one if needed. Thank you very much for your suggestion!
