### ISSUE TITLE
Problem with ajax call and erb partial

### ISSUE THREAD

**Issue by marino-mrc** [platanus/activeadmin_addons#330]
Hi, I'm trying to use a form inside a partial with activeadmin and I'm a bit confused. The problem is that if I use an html.arb file the form doesn't work ( and I'm going to open an issue on activeadmin repository), but if I use html.erb file it (partially) works. 

I mean, if I use my .erb partial with:
form partial: "myform"  it works

but if I use the partial with: (in another part of the code obviously)
respond_to do |format|
        format.html { render partial: "myform" }
end
the jquery part related to activeadmin_addons doesn't work. Select and datepicker are unusable and nothing of all activeadmin_addons jquery stuffs seems to work. Please note that the problem is only when I use the partial using the second example probably because the call happens inside a member_action called by a javascript function (through the html() and load() functions). 

My question is: what I'm doing wrong? Is there a way to "reload" activeadmin_addons js and css in an ajax call? Is there a better way to obtain the same result?
Thank you

**Comment by rjherrera** [comment]
Hi @ntt1985! I'm not sure if I understand the problem correctly, can you provide a bit more of code to try and reproduce the issue? Also, which version are you using (both AA and AA Addons)?

**Comment by ldlsegovia** [comment]
Please, provide more information and reopen if this is still an issue.
