### ISSUE TITLE
Any plans on releasing a new version?

### ISSUE THREAD

**Issue by vfonic** [platanus/activeadmin_addons#338]
I see there's a lot of development going on in the gem and there are some new addons being added, which is great to see!

However, I noticed that no new version of the gem has been released in 2 years now!

Are there any plans to release a new gem version?

Thanks!

**Comment by shawnwonolo** [comment]
Is releasing a new gem version in the roadmap? Would it be helpful for someone to open a PR for this?

Is there a stable commit sha I could use in the interim?

**Comment by IrinaBron** [comment]
I also would be interested to know if there's a new gem version scheduled to be released?

**Comment by rjherrera** [comment]
sorry for the late answer @vfonic @shawnwonolo @IrinaBron! We think we are set to release a new version probably next week. We wanted to test that some other projects that rely on AA addons worked correctly with the webpacker version in the master branch, and as we did, we plan on releasing soon. Thanks for the patience.

**Comment by vfonic** [comment]
Thank you @rjherrera and the team for all the work!

I suggest to leave the issue open until it's resolved (until a new version has been released).

Either way, I'm looking forward for the new version! 🚀
