### ISSUE TITLE
Running `rake tests` adds Webpacker  gem to Gemfile

### ISSUE THREAD

**Issue by vfonic** [platanus/activeadmin_addons#339]
I noticed that, if I run `rake tests`, the Webpacker gem gets added to the `Gemfile`. I haven't seen this as a common practice and it's strange that the test code is adding a gem to a `Gemfile`. There's gotta be a better way to do this?

I'm afraid of running these tests again as I've noticed the tests are adding, removing and modifying files on my filesystem.

**Comment by gmq** [comment]
It should _only_ change things inside the `spec/dummy` folder, to get a proper environment for both setups (sprockets and webpacker), so the only Gemfile being modified _should_ be the one from the fake app.

In any case, we're thinking about alternatives to minimize that kind of thing.

**Comment by vfonic** [comment]
It actually added `'webpacker'` to the gem's `Gemfile`. It is a bit odd setup. I've looked into it a bit and yeah, I see why you did it this way. There's gotta be something like Appraisals where you can have two dummy apps or something along those lines.

I'd guess you could have two `spec/rails_helper.rb` files where they would share the same common setup (which you could move to `spec/spec_helper.rb` since you're not using that file) and just have `ENGINE_ROOT` different.
