### ISSUE TITLE
tags input, incorrect initial value

### ISSUE THREAD

**Issue by dor6-jul** [platanus/activeadmin_addons#341]
using tags input when updating a record I get the selected labels merged into 1.
i use Postgres array column and all is working fine, the problem is the initial value of the tags input (the hidden input) is the array values joined using spaces instead of joined using commas.
when you play with the field ( adding deleting ) it fixes the value to the correct format the problem is when the user updates the model without touching the tag input then all the values are merged into 1 string.

other than that using the input with string array works just fine.

**Comment by rjherrera** [comment]
hi @dor6-jul ! I think I was able to reproduce your error and I will be trying to fix it during the week, thank you for the report!

**Comment by ladyparallel** [comment]
I'm having the same issue, is there a solution yet? @rjherrera

**Comment by rjherrera** [comment]
@ladyparallel hi! I have a working solution but it may break compatibility with other implementations, as this only happens for the postgres-arrays columns. I'll be testing it and I think this friday I'll come up with an answer. Sorry I'm not able to do this faster.

**Comment by shah21** [comment]
Hey did you guys solve this issue?. I have this issue with :tags
