### ISSUE TITLE
Vendor data present in the RubyGems releases

### ISSUE THREAD

**Issue by mensfeld** [platanus/activeadmin_addons#355]
Hey there,

My name is Maciej Mensfeld and I run security & quality assessment for OSS libraries using WhiteSource [Diffend.io](https://diffend.io).

While reviewing the changes for this lib, I noticed, that the vendor directory is being included.

Is this needed? Usually, it's added by mistake and causes:

a) confusion
b) problems when tracking changes
c) extensive library size

This library used to be around 706 KB now it's 81.8MB (most recent 1.8.0 version). It's 118x bigger.

You can see it for example here: https://my.diffend.io/gems/activeadmin_addons/1.1.2/1.2.0

If the presence of vendor data is valid I would love the reasoning. Thanks!

**Comment by ldlsegovia** [comment]
Thanks! I fixed it in v1.8.2
