### ISSUE TITLE
Use same versions for npm package and ruby gem

### ISSUE THREAD

**Issue by filipkis** [platanus/activeadmin_addons#358]
Hi guys and thanks for all the work to modernize this gem with webpacker support. 

I noticed that the npm package is at version 1. Common practice is to have same versioning for npm and gem because they live in the same repository, have shared changelog and likely will be released at the same time. 

I guess there is no urgency to release a new version just to fix this, but keep it in mind for the next release. Might be good to then also make a minor release instead of patch (i.e. go to 1.9.0), so both gem and package version are changed on the same level.

Cheers and thanks again

**Comment by difernandez** [comment]
Hi sorry for the late reply. We are now planning on taking this approach going forward with v2. I'll close this issue now, thanks for the suggestion!

**Comment by cprodhomme** [comment]
Is it possible to push the version 1.10.0 on npm package ?

i'm not ready to move to v2 of activeadmin_addons ? Thanks !

**Comment by difernandez** [comment]
Version 1.10.0 of the gem doesn't have any JS changes beyond version 1.0.0 of the npm package, and we are not planning on backporting any v2 changes to v1, sorry!
