### ISSUE TITLE
Compatibility information of activeadmin_addons of 1.8.2

### ISSUE THREAD

**Issue by ryu-sato** [platanus/activeadmin_addons#360]
Version 1.8.2 of activeadmin_addons requires activeadmin 2.5.0 or higher.
This is the compatibility information.

If you use a version of activeadmin lower than 2.5.0, you will get an error because the number of arguments in the input_html_options method does not match.
Probably https://github.com/activeadmin/activeadmin/pull/5867 is caused.

```
wrong number of arguments (given 2, expected 0)
----
class DateRangeInput < ActiveAdmin::Inputs::Filters::DateRangeInput
  def input_html_options
    super.except(:maxlength, :size).merge({ autocomplete: 'off' })
  end
end
```

**Comment by futuretap** [comment]
This should be fixed or reflected in the gemspec.
