### ISSUE TITLE
Correct the documentation

### ISSUE THREAD

**Issue by bluengreen** [platanus/activeadmin_addons#37]
Please update your documentation to reflect how to actually use this code. Within the setup section of your readme please change this line -

```
//= require activeadmin_addons/all
```
Should be 
```
*= require activeadmin_addons/all
```
//= is for including JS files not CSS 

And this line 
```
#= require activeadmin_addons/all
```
Should be 
```
//= require activeadmin_addons/all
```

**Comment by ldlsegovia** [comment]
@bluengreen the README file is ok, the example is using coffescript and sass like we use in the dummy application.
https://github.com/platanus/activeadmin_addons/blob/master/spec/dummy/app/assets/stylesheets/active_admin.css.scss
https://github.com/platanus/activeadmin_addons/blob/master/spec/dummy/app/assets/javascripts/active_admin.js.coffee
