### ISSUE TITLE
Missing language files since select2_rails has been vendored in 8.0

### ISSUE THREAD

**Issue by etienneCharignon** [platanus/activeadmin_addons#374]
When you decided to vendor select2_rails files with the 8.0 release, you did not import language files.

For example, to use the french translation, select2_rails recommand to require the file `select2_locale_fr` which is missing since 8.0

**Comment by difernandez** [comment]
Hi, sorry for the late reply, we released a new v2 beta, which, among other things, removes select2, so we’ll be closing this issue. [You can see more details here](https://github.com/platanus/activeadmin_addons/releases/tag/v2.0.0.beta.0). Feel free to try it and open a new issue if you find anything there.
