### ISSUE TITLE
Boolean select width issue in filters

### ISSUE THREAD

**Issue by ibnesayeed** [platanus/activeadmin_addons#378]
The `select2` rendering for `boolean` attributes are only taking `80%` width when used in the filter sidebar.

![image](https://user-images.githubusercontent.com/65147/136829785-7468adf5-da95-478d-999c-42d17679bf4b.png)

**Comment by difernandez** [comment]
Thanks for reporting this! With the changes in #448 and #457, present in v2 beta, we are no longer setting a default width of 80%, so the width should now be dictated by whatever you manually set at the input level, or what the theme you are using defines. I'm closing this issue, but feel free to let us know if it's still a problem or if you find something else in the latest version
