### ISSUE TITLE
Add Rails 7 support (CDN?)

### ISSUE THREAD

**Issue by Ar2emis** [platanus/activeadmin_addons#398]
I am not familiar with JS and ways to integrate with Rails 7 but I made changes to use gem via CDN and it works fine as I see. Maybe you should add changes like in my [fork](https://github.com/Ar2emis/activeadmin_addons) v1.10.0. Suggetions are appretiated)

**Comment by difernandez** [comment]
We just released a new v2 beta with better support for Rails 7, so we’ll be closing this issue. [You can see more details here](https://github.com/platanus/activeadmin_addons/releases/tag/v2.0.0.beta.0). Feel free to open a new issue if you find anything.
