### ISSUE TITLE
How to handle paperclip preview when in an another model ?

### ISSUE THREAD

**Issue by anthony-robin** [platanus/activeadmin_addons#40]
Hi,

I have a dedicated model used to handle my paperclip attachments (Picture model with image attribute). How can I used your addons gem in ActiveAdmin index and show views to display the paperclip attachment of my model ? 

Here is the code I tried:
``` ruby
  index do
    image_column { |r| r.picture.image } # How can I choose the size I want ?
    actions
  end
```

``` ruby
  show do
    attributes_table do
      image_row resource.picture.image, style: :thumb # this doesn't work
    end
  end
```

Thanks for your help and this great gem !

**Comment by emilioeduardob** [comment]
Hi Anthony,
Have you tried something like this?
```ruby
 index do
    image_column style: :thumb { |r| r.picture.image } 
    image_column :image,  style: :thumb { |r| r.picture.image } 
   actions
  end
```
```ruby
  show do
    attributes_table do
      image_row style: :thumb { |r| r.picture.image } 
    end
  end
```

PS: I haven't tested the code

**Comment by anthony-robin** [comment]
Thanks for your answer !
I already tried differents combinations to make it working but everytime I got a Ruby syntax error. 
I also tried your examples but none of them did work either :(

**Comment by emilioeduardob** [comment]
Oh, I guess you have to use the other block syntax

```ruby
index do
    image_column :image,  style: :thumb do |r| 
       r.picture.image
    end
   actions
  end

```

ps: this one did work for me

**Comment by anthony-robin** [comment]
I didn't think of using the "do" block syntax.
Thank you very much, it works for me !
