### ISSUE TITLE
Rails 7 with css-bundler

### ISSUE THREAD

**Issue by gap777** [platanus/activeadmin_addons#426]
This project depends upon `sassc-rails`, which causes problems when pulled into a Rails 7 project using css-bundler + tailwindcss. @joker-777 opened up a [PR](https://github.com/platanus/activeadmin_addons/pull/412) to address this, but it was not merged (and then eventually closed). 

Can we work together to get this change made?

**Comment by difernandez** [comment]
Hi, sorry for the late reply. We are planning a beta release for a new major version of this gem, which will drop support for sprockets, among other things. Theses changes will include the removal of sassc and sassc-rails dependencies. We’ll leave the related issues open for now, at least until the release of this version, but will be closing related PRs, as we might need to include similar changes in the removal of sprockets support.

**Comment by gap777** [comment]
Super! How will I know when you release that major new version?

**Comment by difernandez** [comment]
You can watch the repository to get notified when the new release is here. You can choose to only be notified for releases, if you prefer

**Comment by difernandez** [comment]
We released a new v2 beta, which, among other things, removes sassc-rails, so we’ll be closing this issue. [You can see more details here](https://github.com/platanus/activeadmin_addons/releases/tag/v2.0.0.beta.0). Feel free to open a new issue if you find anything.

**Comment by gap777** [comment]
Great news! @difernandez when do you expect v2 to leave beta?

**Comment by difernandez** [comment]
Unfortunately, we don't have an ETA at the moment. We have to test it some more in our projects and make sure there aren't any big issues related to the changes
