### ISSUE TITLE
[Question] Can `nested_select` be used within the same model?

### ISSUE THREAD

**Issue by raulperezalejo** [platanus/activeadmin_addons#465]
Hello, as the title of this issues say, I have an scenario where I need to select two enum, one dependant on the other.
 
I have looked at the `nested_select` and it is not possible since it is very wired to the existence of classes and relations, but anyway wanted to ask to see if there is a workaround or if anyone has a recommendation of how to implement this besides doing it from scratch.

Thanks in advance.

**Comment by difernandez** [comment]
As you were saying, the nested select's intended use is with models and associations, so there is no support for a use case like you describe. Unfortunately, you would have to do this from scratch with JS/JQuery.
Thanks for your question, but I'm closing this, as we currently don't have plans to add support for something like this.

**Comment by raulperezalejo** [comment]
Thanks for your answer.
