### ISSUE TITLE
[FR] Release gem with latest changes

### ISSUE THREAD

**Issue by mario-amazing** [platanus/activeadmin_addons#507]
@rjherrera, Could you Release gem with latest changes?
Thanks in advance!

**Comment by rjherrera** [comment]
hi there @mario-amazing :)

I am doing it as we speak. Already updated v1 to [1.10.2](https://github.com/platanus/activeadmin_addons/pull/509), and will update v2 to beta 4 shortly.

**Comment by rjherrera** [comment]
done :)

**Comment by mario-amazing** [comment]
@rjherrera, thank a lot!
