### ISSUE TITLE
dragonfly integration?

### ISSUE THREAD

**Issue by rhymes** [platanus/activeadmin_addons#55]
It is possible to have https://github.com/markevans/dragonfly integration other than paperclip?
I would happily try to code it myself and submit a PR but I may need some directions :)

**Comment by ldlsegovia** [comment]
@rhymes I saw your PR. It looks great but for now, we’re only supporting paperclip as it is the most used

**Comment by rhymes** [comment]
@ldlsegovia I understand but my patch does not conflict with Paperclip, it's just a support for a widely used library (more than 1 million downloads on Ruby Toolbox https://www.ruby-toolbox.com/projects/dragonfly )
