### ISSUE TITLE
Update select2-rails to 4.0+

### ISSUE THREAD

**Issue by rhymes** [platanus/activeadmin_addons#56]
Version 4 has been out since September 2015, it would be nice to be able to use the latest version

**Comment by rhymes** [comment]
@emilioeduardob any idea how I can help?

**Comment by emilioeduardob** [comment]
hey @rhymes, it'd be great if you could start a PR =). I haven't found the time to do it myself just yet

**Comment by emilioeduardob** [comment]
work has started on the branch https://github.com/platanus/activeadmin_addons/tree/select2-v4

**Comment by rhymes** [comment]
any news on this?

**Comment by mabdelfattah** [comment]
I made the updates in this Pull Requests and it is working fine.
https://github.com/platanus/activeadmin_addons/pull/121
