### ISSUE TITLE
Add ransack as a dependency

### ISSUE THREAD

**Issue by sudoaza** [platanus/activeadmin_addons#59]
i installed activeadmin_addons in my project but when i went to the admin page i got an error about missing ransack. Adding it to my Gemfile and installing it fixed it. It should be a dependency.

**Comment by emilioeduardob** [comment]
Well, that's weird since ActiveAdmin already depends on Ransack(at least 1.0). What version are you using?

**Comment by sudoaza** [comment]
i'm using rails 3.2.14 and active admin 0.6.3
but this is for rails 2 right?

**Comment by emilioeduardob** [comment]
No, it's for Rails 4.x and ActiveAdmin 1.0 (0.6 uses metasearch instead of ransack)

**Comment by sudoaza** [comment]
ok thanks i'll check if i can upgrade to ActiveAdmin 1.0

**Comment by blackjid** [comment]
This issue made me remember this discussion https://github.com/platanus/activeadmin_addons/pull/43
If activeadmin was defined as a dependency of activeadmin_addons @sudoaza would have realize about the problem in the instant he try to add activeadmin_addons to his project.

Just a thought
