### ISSUE TITLE
Ajax search only working with rootless response

### ISSUE THREAD

**Issue by ldlsegovia** [platanus/activeadmin_addons#60]
Actually the gem works with responses like this:

```json
[{"id":1,"name":"Chile"}, {"id":2,"name":"Argentina"}]
```

It would be desirable to work with the following response too:

```json
{"countries":[{"id":1,"name":"Chile"}, {"id":2,"name":"Argentina"}]}
```

this is an issue with [select2_search](https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_search.md) and [select2_nested_select](https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_nested_select.md)

it would be nice to infer the root. For example, having:

```ruby
f.input :category_id, as: :search_select, url: admin_categories_path, fields: [:name], display_name: 'name', minimum_input_length: 1
```

if `category_id` is the attribute, we should infer `categories` root. If `response.categories` is null, we should infer a rootless response.

what do you think about this @emilioeduardob ?

**Comment by emilioeduardob** [comment]
Agree. I like the proposed solution
