### ISSUE TITLE
Paperclip attachment: fileicon for MP3

### ISSUE THREAD

**Issue by anthony-robin** [platanus/activeadmin_addons#64]
It could be a good idea to add the MP3 file icon for Paperclip attachment addon, as it's one of the most used audio format.

**Comment by agustinf** [comment]
Anthony! We haven't needed MP3 attachments, but if you do, go ahead and do a pull request, we would merge it gladly. Thanks for supporting open source!

**Comment by anthony-robin** [comment]
Sure, I can make a pull request. 
Where did you find all your fileicons (I noticed they have all the same construction and I wouldn't add a different style) ?
Thanks !

**Comment by ldlsegovia** [comment]
@anthony-robin we use https://github.com/anderson/rails-file-icons/tree/master/vendor/assets/images/fileicons

**Comment by robdvr** [comment]
Added a pull request here!
https://github.com/platanus/activeadmin_addons/pull/69

**Comment by ldlsegovia** [comment]
thanks @robdvr
