### ISSUE TITLE
Paperclip attachment: error with assets not being precompiled

### ISSUE THREAD

**Issue by anthony-robin** [platanus/activeadmin_addons#65]
When using the addon, I get this error:
```
Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( fileicons/file_extension_unknown.png )` to `config/initializers/assets.rb` and restart your server
```

Maybe you should handle that directly in your gem or add README instructions saying to precompile fileicons ?
`Rails.application.config.assets.precompile += %w( fileicons/*.png )`

**Comment by robdvr** [comment]
Sent a pull request here:
https://github.com/platanus/activeadmin_addons/pull/68

**Comment by ldlsegovia** [comment]
thanks!
