### ISSUE TITLE
select2 input width?

### ISSUE THREAD

**Issue by niksfirefly** [platanus/activeadmin_addons#67]
Is it possible to change width for specific select2 inputs?

**Comment by ldlsegovia** [comment]
@niksfirefly no, it's harcoded [here](https://github.com/platanus/activeadmin_addons/blob/master/app/assets/javascripts/activeadmin_addons/select2.js#L18), [here](https://github.com/platanus/activeadmin_addons/blob/master/app/assets/javascripts/activeadmin_addons/select2.js#L57) and [here](https://github.com/platanus/activeadmin_addons/blob/master/app/assets/javascripts/activeadmin_addons/select2.js#L134). We should have used a constant at least 😞
If you want to contribute, you can do a PR passing the with as data attribute (as we do with [url param](https://github.com/platanus/activeadmin_addons/blob/master/app/assets/javascripts/activeadmin_addons/select2.js#L63) for example) and use a constant to set default to 80% if `with` is not present.

**Comment by niksfirefly** [comment]
thx for response
Meanwhile I found out 2 simple solutions and i can live with that
1.modify width for .select2-container with CSS
2.use Jquery to access select input and set select2 width property to different from initialization
regards
