### ISSUE TITLE
invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by manme** [platanus/activeadmin_addons#71]
Rails 4.2.6
ActiveAdmin 1.0.0.pre2

invalid byte sequence in UTF-8
Occur when i set `//= require activeadmin_addons/all` in my `active_admin.scss`

Full log: 

ArgumentError - invalid byte sequence in UTF-8:
  less-rails (2.7.1) lib/less/rails/import_processor.rb:23:in `scan'
  less-rails (2.7.1) lib/less/rails/import_processor.rb:23:in `depend_on'
  less-rails (2.7.1) lib/less/rails/import_processor.rb:27:in `block in depend_on'
  less-rails (2.7.1) lib/less/rails/import_processor.rb:24:in `each'
  less-rails (2.7.1) lib/less/rails/import_processor.rb:24:in `depend_on'
  less-rails (2.7.1) lib/less/rails/import_processor.rb:18:in `evaluate'
  tilt (2.0.4) lib/tilt/template.rb:102:in `render'
  sprockets (3.6.0) lib/sprockets/legacy_tilt_processor.rb:25:in `call'
  sprockets (3.6.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.6.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.6.0) lib/sprockets/processor_utils.rb:56:in `reverse_each'
  sprockets (3.6.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.6.0) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.6.0) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.6.0) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  sprockets (3.6.0) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.6.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.6.0) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.6.0) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (3.6.0) lib/sprockets/utils.rb:183:in `dfs'
  sprockets (3.6.0) lib/sprockets/bundle.rb:24:in `call'
  sprockets (3.6.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.6.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.6.0) lib/sprockets/processor_utils.rb:56:in `reverse_each'
  sprockets (3.6.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.6.0) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.6.0) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.6.0) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  sprockets (3.6.0) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.6.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.6.0) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.6.0) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.6.0) lib/sprockets/base.rb:92:in `[]'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:341:in `find_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:333:in `find_debug_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:216:in `block in lookup_debug_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:229:in `block in resolve_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:228:in `each'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:228:in `detect'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:228:in `resolve_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:215:in `lookup_debug_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:157:in `block in stylesheet_link_tag'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:156:in `map'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:156:in `stylesheet_link_tag'
  arbre (1.0.3) lib/arbre/element.rb:180:in `method_missing'
  activeadmin (1.0.0.pre2) lib/active_admin/views/pages/base.rb:27:in `block (2 levels) in build_active_admin_head'
  activeadmin (1.0.0.pre2) lib/active_admin/views/pages/base.rb:26:in `each'
  activeadmin (1.0.0.pre2) lib/active_admin/views/pages/base.rb:26:in `block in build_active_admin_head'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  activeadmin (1.0.0.pre2) lib/active_admin/views/pages/base.rb:24:in `build_active_admin_head'
  activeadmin (1.0.0.pre2) lib/active_admin/views/pages/base.rb:9:in `build'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  activeadmin (1.0.0.pre2) app/views/active_admin/resource/index.html.arb:2:in `block in ___sers_mikhail__rbenv_versions_______lib_ruby_gems_______gems_activeadmin_______pre__app_views_active_admin_resource_index_html_arb___2768989945323213763_70279960401700'
  arbre (1.0.3) lib/arbre/context.rb:45:in `instance_eval'
  arbre (1.0.3) lib/arbre/context.rb:45:in `initialize'
  activeadmin (1.0.0.pre2) app/views/active_admin/resource/index.html.arb:1:in `new'
  activeadmin (1.0.0.pre2) app/views/active_admin/resource/index.html.arb:1:in `___sers_mikhail__rbenv_versions_______lib_ruby_gems_______gems_activeadmin_______pre__app_views_active_admin_resource_index_html_arb___2768989945323213763_70279960401700'
  actionview (4.2.6) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.6) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.6) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.6) lib/action_view/template.rb:143:in `render'
  actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.6) lib/action_view/renderer/renderer.rb:46:in `render_template'
  actionview (4.2.6) lib/action_view/renderer/renderer.rb:27:in `render'
  actionview (4.2.6) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.6) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.6) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.6) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.6) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.6) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.6) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.6) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/mikhail/.rbenv/versions/2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.6) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:43:in `render'
  wicked_pdf (1.0.6) lib/wicked_pdf/pdf_helper.rb:22:in `render_with_wicked_pdf'
  responders (2.2.0) lib/action_controller/responder.rb:238:in `default_render'
  responders (2.2.0) lib/action_controller/responder.rb:170:in `to_html'
  responders (2.2.0) lib/responders/flash_responder.rb:107:in `to_html'
  responders (2.2.0) lib/action_controller/responder.rb:163:in `respond'
  responders (2.2.0) lib/action_controller/responder.rb:156:in `call'
  responders (2.2.0) lib/action_controller/respond_with.rb:205:in `respond_with'
  inherited_resources (1.6.0) lib/inherited_resources/actions.rb:7:in `index'
  activeadmin (1.0.0.pre2) lib/active_admin/resource_controller/streaming.rb:12:in `index'
  actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.6) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `catch'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'

**Comment by ldlsegovia** [comment]
I've tested in a fresh rails app and I can't reproduce the error. I think the problem is not related with addons.

<img width="562" alt="screen shot 2016-06-18 at 6 02 42 pm" src="https://cloud.githubusercontent.com/assets/3026413/16173661/129e4342-357f-11e6-8dc9-6c8cc05c0595.png">
