### ISSUE TITLE
ActiveAdmin Globalize addon ?

### ISSUE THREAD

**Issue by anthony-robin** [platanus/activeadmin_addons#75]
As you build awesome enhancement for ActiveAdmin, did you plan to develop one to handle the **Globalize** gem to resources form ?  
The [only gem](https://github.com/unmantained-activeadmin-plugins/activeadmin-globalize) doing that is not maintained anymore and might no be working properly with **Rails 5**

That would be amazing to include it in your addons !

**Comment by ldlsegovia** [comment]
@anthony-robin I think it's a good idea but we maintain tools we use in Platanus only.
Sorry for a late response...
