### ISSUE TITLE
Filtered value is not displayed after filter is applied

### ISSUE THREAD

**Issue by DmitryRibalka** [platanus/activeadmin_addons#81]
Hello,
I could setup ajax for filter

  filter :user_id_in, as: :search_select, multiple: true, url: '/admin/users.json',
          fields: ['contact_f_name', 'contact_l_name'], display_name: :full_name, minimum_input_length: 2

It filters and works, except select2 input has no selected value after.

http://127.0.0.1:3000/admin/device_tokens?utf8=%E2%9C%93&q%5Buser_id_in%5D=165&commit=Filter&order=id_desc

I see  a request to DB to select correct user for index page

``` json
{
  "utf8": "✓",
  "q": {
    "user_id_in": "165"
  },
  "commit": "Filter",
  "order": "id_desc",
  "controller": "admin/device_tokens",
  "action": "index"
}

```

SELECT COUNT(*) FROM `device_tokens` WHERE `device_tokens`.`user_id` IN (165)

But input has no label with users's name

``` html
<input id="q_user_id_in" class="select2-ajax " data-fields="[&quot;contact_f_name&quot;,&quot;contact_l_name&quot;]" data-url="/admin/users.json" data-display_name="full_name" data-minimum_input_length="2" type="text" value="165" name="q[user_id_in]" tabindex="-1" title="User id in*" style="display: none;">
```

Is it misconfiguration or a bug?

My final goal is to have select2 input that supports multiselect + paging (to reduce html's page weight). Is this possible btw? 

Thanks.

**Comment by ldlsegovia** [comment]
You can use [`search_select`](https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_search.md#ajax-search) as an input in forms only. And [these](https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_search.md#options) are the valid options.
