### ISSUE TITLE
select2_search URL Question

### ISSUE THREAD

**Issue by maxexcloo** [platanus/activeadmin_addons#82]
Hello!
Firstly I'd like to thank you for your plugin, it's fantastic!
I have a query relating to the select2_search AJAX functionality, I am unable to get it working.

Adding `filter :Bank_id, as: :search_select, fields: [:bsb, :institution, :name, :address, :city, :state, :postcode], url: admin_banks_path` results in an `undefined local variable or method`admin_banks_path' for #ActiveAdmin::ResourceDSL:0x007fda93358ed0` error...

My routes are as follows:
`                          Prefix Verb   URI Pattern                                 Controller#Action
                      admin_root GET    /admin(.:format)                            admin/dashboard#index
              import_admin_banks GET    /admin/banks/import(.:format)               admin/banks#import
           do_import_admin_banks POST   /admin/banks/do_import(.:format)            admin/banks#do_import
        batch_action_admin_banks POST   /admin/banks/batch_action(.:format)         admin/banks#batch_action
                     admin_banks GET    /admin/banks(.:format)                      admin/banks#index
                                 POST   /admin/banks(.:format)                      admin/banks#create
                  new_admin_bank GET    /admin/banks/new(.:format)                  admin/banks#new
                 edit_admin_bank GET    /admin/banks/:id/edit(.:format)             admin/banks#edit
                      admin_bank GET    /admin/banks/:id(.:format)                  admin/banks#show
                                 PATCH  /admin/banks/:id(.:format)                  admin/banks#update
                                 PUT    /admin/banks/:id(.:format)                  admin/banks#update
      history_admin_bank_account GET    /admin/bank_accounts/:id/history(.:format)  admin/bank_accounts#history
      import_admin_bank_accounts GET    /admin/bank_accounts/import(.:format)       admin/bank_accounts#import
   do_import_admin_bank_accounts POST   /admin/bank_accounts/do_import(.:format)    admin/bank_accounts#do_import
batch_action_admin_bank_accounts POST   /admin/bank_accounts/batch_action(.:format) admin/bank_accounts#batch_action
             admin_bank_accounts GET    /admin/bank_accounts(.:format)              admin/bank_accounts#index
                                 POST   /admin/bank_accounts(.:format)              admin/bank_accounts#create
          new_admin_bank_account GET    /admin/bank_accounts/new(.:format)          admin/bank_accounts#new
         edit_admin_bank_account GET    /admin/bank_accounts/:id/edit(.:format)     admin/bank_accounts#edit
              admin_bank_account GET    /admin/bank_accounts/:id(.:format)          admin/bank_accounts#show
                                 PATCH  /admin/bank_accounts/:id(.:format)          admin/bank_accounts#update
                                 PUT    /admin/bank_accounts/:id(.:format)          admin/bank_accounts#update
                 admin_dashboard GET    /admin/dashboard(.:format)                  admin/dashboard#index
           history_admin_patient GET    /admin/patients/:id/history(.:format)       admin/patients#history
           import_admin_patients GET    /admin/patients/import(.:format)            admin/patients#import
        do_import_admin_patients POST   /admin/patients/do_import(.:format)         admin/patients#do_import
     batch_action_admin_patients POST   /admin/patients/batch_action(.:format)      admin/patients#batch_action
                  admin_patients GET    /admin/patients(.:format)                   admin/patients#index
                                 POST   /admin/patients(.:format)                   admin/patients#create
               new_admin_patient GET    /admin/patients/new(.:format)               admin/patients#new
              edit_admin_patient GET    /admin/patients/:id/edit(.:format)          admin/patients#edit
                   admin_patient GET    /admin/patients/:id(.:format)               admin/patients#show
                                 PATCH  /admin/patients/:id(.:format)               admin/patients#update
                                 PUT    /admin/patients/:id(.:format)               admin/patients#update
              history_admin_user GET    /admin/users/:id/history(.:format)          admin/users#history
              import_admin_users GET    /admin/users/import(.:format)               admin/users#import
           do_import_admin_users POST   /admin/users/do_import(.:format)            admin/users#do_import
        batch_action_admin_users POST   /admin/users/batch_action(.:format)         admin/users#batch_action
                     admin_users GET    /admin/users(.:format)                      admin/users#index
                                 POST   /admin/users(.:format)                      admin/users#create
                  new_admin_user GET    /admin/users/new(.:format)                  admin/users#new
                 edit_admin_user GET    /admin/users/:id/edit(.:format)             admin/users#edit
                      admin_user GET    /admin/users/:id(.:format)                  admin/users#show
                                 PATCH  /admin/users/:id(.:format)                  admin/users#update
                                 PUT    /admin/users/:id(.:format)                  admin/users#update
                  admin_comments GET    /admin/comments(.:format)                   admin/comments#index
                                 POST   /admin/comments(.:format)                   admin/comments#create
                   admin_comment GET    /admin/comments/:id(.:format)               admin/comments#show
                                 DELETE /admin/comments/:id(.:format)               admin/comments#destroy
                new_user_session GET    /users/sign_in(.:format)                    devise/sessions#new
                    user_session POST   /users/sign_in(.:format)                    devise/sessions#create
            destroy_user_session DELETE /users/sign_out(.:format)                   devise/sessions#destroy
                   user_password POST   /users/password(.:format)                   devise/passwords#create
               new_user_password GET    /users/password/new(.:format)               devise/passwords#new
              edit_user_password GET    /users/password/edit(.:format)              devise/passwords#edit
                                 PATCH  /users/password(.:format)                   devise/passwords#update
                                 PUT    /users/password(.:format)                   devise/passwords#update
        cancel_user_registration GET    /users/cancel(.:format)                     registrations#cancel
               user_registration POST   /users(.:format)                            registrations#create
           new_user_registration GET    /users/sign_up(.:format)                    registrations#new
          edit_user_registration GET    /users/edit(.:format)                       registrations#edit
                                 PATCH  /users(.:format)                            registrations#update
                                 PUT    /users(.:format)                            registrations#update
                                 DELETE /users(.:format)                            registrations#destroy
               user_confirmation POST   /users/confirmation(.:format)               devise/confirmations#create
           new_user_confirmation GET    /users/confirmation/new(.:format)           devise/confirmations#new
                                 GET    /users/confirmation(.:format)               devise/confirmations#show
                          blazer        /bi                                         Blazer::Engine
                     rails_admin        /database                                   RailsAdmin::Engine
                  accommodations GET    /accommodations(.:format)                   accommodations#index
                                 POST   /accommodations(.:format)                   accommodations#create
               new_accommodation GET    /accommodations/new(.:format)               accommodations#new
              edit_accommodation GET    /accommodations/:id/edit(.:format)          accommodations#edit
                   accommodation GET    /accommodations/:id(.:format)               accommodations#show
                                 PATCH  /accommodations/:id(.:format)               accommodations#update
                                 PUT    /accommodations/:id(.:format)               accommodations#update
                                 DELETE /accommodations/:id(.:format)               accommodations#destroy
                   bank_accounts GET    /bank_accounts(.:format)                    bank_accounts#index
                                 POST   /bank_accounts(.:format)                    bank_accounts#create
                new_bank_account GET    /bank_accounts/new(.:format)                bank_accounts#new
               edit_bank_account GET    /bank_accounts/:id/edit(.:format)           bank_accounts#edit
                    bank_account GET    /bank_accounts/:id(.:format)                bank_accounts#show
                                 PATCH  /bank_accounts/:id(.:format)                bank_accounts#update
                                 PUT    /bank_accounts/:id(.:format)                bank_accounts#update
                                 DELETE /bank_accounts/:id(.:format)                bank_accounts#destroy
                         escorts GET    /escorts(.:format)                          escorts#index
                                 POST   /escorts(.:format)                          escorts#create
                      new_escort GET    /escorts/new(.:format)                      escorts#new
                     edit_escort GET    /escorts/:id/edit(.:format)                 escorts#edit
                          escort GET    /escorts/:id(.:format)                      escorts#show
                                 PATCH  /escorts/:id(.:format)                      escorts#update
                                 PUT    /escorts/:id(.:format)                      escorts#update
                                 DELETE /escorts/:id(.:format)                      escorts#destroy
                        patients GET    /patients(.:format)                         patients#index
                                 POST   /patients(.:format)                         patients#create
                     new_patient GET    /patients/new(.:format)                     patients#new
                    edit_patient GET    /patients/:id/edit(.:format)                patients#edit
                         patient GET    /patients/:id(.:format)                     patients#show
                                 PATCH  /patients/:id(.:format)                     patients#update
                                 PUT    /patients/:id(.:format)                     patients#update
                                 DELETE /patients/:id(.:format)                     patients#destroy
                        receipts GET    /receipts(.:format)                         receipts#index
                                 POST   /receipts(.:format)                         receipts#create
                     new_receipt GET    /receipts/new(.:format)                     receipts#new
                    edit_receipt GET    /receipts/:id/edit(.:format)                receipts#edit
                         receipt GET    /receipts/:id(.:format)                     receipts#show
                                 PATCH  /receipts/:id(.:format)                     receipts#update
                                 PUT    /receipts/:id(.:format)                     receipts#update
                                 DELETE /receipts/:id(.:format)                     receipts#destroy
                 representatives GET    /representatives(.:format)                  representatives#index
                                 POST   /representatives(.:format)                  representatives#create
              new_representative GET    /representatives/new(.:format)              representatives#new
             edit_representative GET    /representatives/:id/edit(.:format)         representatives#edit
                  representative GET    /representatives/:id(.:format)              representatives#show
                                 PATCH  /representatives/:id(.:format)              representatives#update
                                 PUT    /representatives/:id(.:format)              representatives#update
                                 DELETE /representatives/:id(.:format)              representatives#destroy
                  travel_diaries GET    /travel_diaries(.:format)                   travel_diaries#index
                                 POST   /travel_diaries(.:format)                   travel_diaries#create
                new_travel_diary GET    /travel_diaries/new(.:format)               travel_diaries#new
               edit_travel_diary GET    /travel_diaries/:id/edit(.:format)          travel_diaries#edit
                    travel_diary GET    /travel_diaries/:id(.:format)               travel_diaries#show
                                 PATCH  /travel_diaries/:id(.:format)               travel_diaries#update
                                 PUT    /travel_diaries/:id(.:format)               travel_diaries#update
                                 DELETE /travel_diaries/:id(.:format)               travel_diaries#destroy
                        journeys GET    /journeys(.:format)                         journeys#index
                                 POST   /journeys(.:format)                         journeys#create
                     new_journey GET    /journeys/new(.:format)                     journeys#new
                    edit_journey GET    /journeys/:id/edit(.:format)                journeys#edit
                         journey GET    /journeys/:id(.:format)                     journeys#show
                                 PATCH  /journeys/:id(.:format)                     journeys#update
                                 PUT    /journeys/:id(.:format)                     journeys#update
                                 DELETE /journeys/:id(.:format)                     journeys#destroy
     accommodations_get_business GET    /accommodations/get_business(.:format)      accommodations#get_business
                                 GET    /pages/:page(.:format)                      pages#show
                            root GET    /                                           pages#show {:page=>"home"}
                                 GET    /                                           pages#show

Routes for Blazer::Engine:
      run_queries POST   /queries/run(.:format)            blazer/queries#run
   cancel_queries POST   /queries/cancel(.:format)         blazer/queries#cancel
    refresh_query POST   /queries/:id/refresh(.:format)    blazer/queries#refresh
   tables_queries GET    /queries/tables(.:format)         blazer/queries#tables
   schema_queries GET    /queries/schema(.:format)         blazer/queries#schema
          queries GET    /queries(.:format)                blazer/queries#index
                  POST   /queries(.:format)                blazer/queries#create
        new_query GET    /queries/new(.:format)            blazer/queries#new
       edit_query GET    /queries/:id/edit(.:format)       blazer/queries#edit
            query GET    /queries/:id(.:format)            blazer/queries#show
                  PATCH  /queries/:id(.:format)            blazer/queries#update
                  PUT    /queries/:id(.:format)            blazer/queries#update
                  DELETE /queries/:id(.:format)            blazer/queries#destroy
        run_check GET    /checks/:id/run(.:format)         blazer/checks#run
           checks GET    /checks(.:format)                 blazer/checks#index
                  POST   /checks(.:format)                 blazer/checks#create
        new_check GET    /checks/new(.:format)             blazer/checks#new
       edit_check GET    /checks/:id/edit(.:format)        blazer/checks#edit
            check PATCH  /checks/:id(.:format)             blazer/checks#update
                  PUT    /checks/:id(.:format)             blazer/checks#update
                  DELETE /checks/:id(.:format)             blazer/checks#destroy
refresh_dashboard POST   /dashboards/:id/refresh(.:format) blazer/dashboards#refresh
       dashboards GET    /dashboards(.:format)             blazer/dashboards#index
                  POST   /dashboards(.:format)             blazer/dashboards#create
    new_dashboard GET    /dashboards/new(.:format)         blazer/dashboards#new
   edit_dashboard GET    /dashboards/:id/edit(.:format)    blazer/dashboards#edit
        dashboard GET    /dashboards/:id(.:format)         blazer/dashboards#show
                  PATCH  /dashboards/:id(.:format)         blazer/dashboards#update
                  PUT    /dashboards/:id(.:format)         blazer/dashboards#update
                  DELETE /dashboards/:id(.:format)         blazer/dashboards#destroy
             root GET    /                                 blazer/queries#home

Routes for RailsAdmin::Engine:
    dashboard GET         /                                      rails_admin/main#dashboard
  bulk_delete POST|DELETE /:model_name/bulk_delete(.:format)     rails_admin/main#bulk_delete
       export GET|POST    /:model_name/export(.:format)          rails_admin/main#export
history_index GET|PUT     /:model_name/history(.:format)         rails_admin/main#history_index
        index GET|POST    /:model_name(.:format)                 rails_admin/main#index
          new GET|POST    /:model_name/new(.:format)             rails_admin/main#new
       import GET|POST    /:model_name/import(.:format)          rails_admin/main#import
  bulk_action POST        /:model_name/bulk_action(.:format)     rails_admin/main#bulk_action
       delete GET|DELETE  /:model_name/:id/delete(.:format)      rails_admin/main#delete
         edit GET|PUT     /:model_name/:id/edit(.:format)        rails_admin/main#edit
 history_show GET         /:model_name/:id/history(.:format)     rails_admin/main#history_show
         show GET         /:model_name/:id(.:format)             rails_admin/main#show
  show_in_app GET         /:model_name/:id/show_in_app(.:format) rails_admin/main#show_in_app`

**Comment by risinglf** [comment]
I have the same problem. Maybe the select2 is usable only as an input field? 

Can we use the same syntax to build a filter with select2?

**Comment by ldlsegovia** [comment]
Hi! @maxexcloo, I'm glad you like. As @risinglf said, [`search_select`](https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_search.md) can be used as input in forms only.

**Comment by emilioeduardob** [comment]
I added a PR that maybe is good for this
