### ISSUE TITLE
[Nested Select] parent id is incorrect when validation error

### ISSUE THREAD

**Issue by hotanlamvnn** [platanus/activeadmin_addons#91]
**Model A, B, C**

B belongs_to A
C belongs_to C

`validates :B_id, presence: true` in model C

In ActiveAdmin C:

Step 1: select A_id = 1
Step 2: don't select B_id
Step 3: Click submit => **Error validation**
Step 4: select A_id = 2 or 3,4,5...
Now, A_id still = 1

**Comment by ldlsegovia** [comment]
I can't reproduce this issue. Can you show me a real scenario?
Please, provide A, B and C models and Active Admin's file.

**Comment by mf222** [comment]
Hi @hotanlamvnn, I could't reproduce your error either. If you still have this problem please let us know in a new issue with more information about the context, like the way you're using `nested_select` in your admin files.
