### ISSUE TITLE
Enable allowClear in select2_search

### ISSUE THREAD

**Issue by mabdelfattah** [platanus/activeadmin_addons#95]
When I select any item from the results in select2_search (AJAX one), I can't find the (x) button to clear my selection. This is happening only the AJAX one not the normal one.

**Comment by maxexcloo** [comment]
I would like this also, did you ever find a solution?

**Comment by mabdelfattah** [comment]
Will do it soon and will do a pull request.

**Comment by mabdelfattah** [comment]
@maxexcloo pull request initiated with this enhancement.

**Comment by Alxzu** [comment]
@mabdelfattah Hi, is this supposed to be used on the activeadmin setup? Something like this??
```
f.input :advertiser_id, as: :search_select, url: admin_contents_advertisers_search_path,
                              fields: %i(email), display_name: 'email',
                              response_root: 'advertisers',
                              allowClear: false,
                              order_by: 'email_asc'
```

`allowClear` or `allow_clear`? Thanks

**Comment by mabdelfattah** [comment]
It should be `allow_clear`
