### ISSUE TITLE
Use default select in each select

### ISSUE THREAD

**Issue by ignacio-chiazzo** [platanus/activeadmin_addons#96]
I have a huge application that has a lot of selects and inputs. I would like to add this library to my project and apply the select to three of four selects.

 The problem here is that I don't want to add default-select to each of selects. Is there a way to avoid this? and specify the selects that I want to use this library?

**Comment by ldlsegovia** [comment]
https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_default.md

**Comment by ignacio-chiazzo** [comment]
Thanks for adding such an awesome feature!
